[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.github.davidmoten:rxjava2-http:jar:0.1.24-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-surefire-plugin @ line 186, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] -----------------< com.github.davidmoten:rxjava2-http >-----------------
[INFO] Building rxjava2-http 0.1.24-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (default) @ rxjava2-http ---
[INFO] argLine set to -javaagent:/home/jdbl/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/tmp/tmp08_viptj/rxjava2-http/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rxjava2-http ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /tmp/tmp08_viptj/rxjava2-http/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ rxjava2-http ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to /tmp/tmp08_viptj/rxjava2-http/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ rxjava2-http ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ rxjava2-http ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 21 source files to /tmp/tmp08_viptj/rxjava2-http/target/test-classes
[INFO] /tmp/tmp08_viptj/rxjava2-http/src/test/java/org/davidmoten/rx2/io/Servers.java: /tmp/tmp08_viptj/rxjava2-http/src/test/java/org/davidmoten/rx2/io/Servers.java uses or overrides a deprecated API.
[INFO] /tmp/tmp08_viptj/rxjava2-http/src/test/java/org/davidmoten/rx2/io/Servers.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ rxjava2-http ---
[INFO] Surefire report directory: /tmp/tmp08_viptj/rxjava2-http/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.davidmoten.rx2.io.ClientTest
isUtilityClass
test4000ByteStream
2020-08-03 11:19:05.027 INFO  org.eclipse.jetty.util.log - Logging initialized @710ms to org.eclipse.jetty.util.log.Slf4jLog
2020-08-03 11:19:05.204 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:05.254 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@6f3bd37f{/,null,AVAILABLE}
2020-08-03 11:19:05.280 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@4b31a708{HTTP/1.1,[http/1.1]}{0.0.0.0:43105}
2020-08-03 11:19:05.280 INFO  org.eclipse.jetty.server.Server - Started @964ms
0s:1
numBytes=4000, 3048 items/s, 11.627MB/s
2020-08-03 11:19:05.619 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@4b31a708{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:05.626 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@6f3bd37f{/,null,UNAVAILABLE}
test400ByteStream
2020-08-03 11:19:05.628 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:05.630 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@384472bf{/,null,AVAILABLE}
2020-08-03 11:19:05.631 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@45f9d394{HTTP/1.1,[http/1.1]}{0.0.0.0:46145}
2020-08-03 11:19:05.632 INFO  org.eclipse.jetty.server.Server - Started @1316ms
0s:1
numBytes=400, 50505 items/s, 19.266MB/s
2020-08-03 11:19:05.831 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@45f9d394{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:05.832 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@384472bf{/,null,UNAVAILABLE}
test40ByteStream
2020-08-03 11:19:05.834 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:05.836 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@600bbf9e{/,null,AVAILABLE}
2020-08-03 11:19:05.837 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@3b8507df{HTTP/1.1,[http/1.1]}{0.0.0.0:40001}
2020-08-03 11:19:05.837 INFO  org.eclipse.jetty.server.Server - Started @1521ms
0s:1
0s:100001
numBytes=40, 117370 items/s, 4.477MB/s
2020-08-03 11:19:06.690 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@3b8507df{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:06.691 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@600bbf9e{/,null,UNAVAILABLE}
testBackpressure
2020-08-03 11:19:06.698 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:06.699 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@26d40c77{/,null,AVAILABLE}
2020-08-03 11:19:06.700 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@7cc1f72c{HTTP/1.1,[http/1.1]}{0.0.0.0:46569}
2020-08-03 11:19:06.700 INFO  org.eclipse.jetty.server.Server - Started @2385ms
2020-08-03 11:19:08.230 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@7cc1f72c{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:08.230 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@26d40c77{/,null,UNAVAILABLE}
testBadUrl
testCancel
2020-08-03 11:19:08.233 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:08.234 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@1b4a3a1{/,null,AVAILABLE}
2020-08-03 11:19:08.235 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@3eac2e8a{HTTP/1.1,[http/1.1]}{0.0.0.0:41325}
2020-08-03 11:19:08.235 INFO  org.eclipse.jetty.server.Server - Started @3919ms
2020-08-03 11:19:08.244 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@3eac2e8a{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:08.245 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@1b4a3a1{/,null,UNAVAILABLE}
testClientNegativeReadTimeoutThrows
testClientNegativeTimeoutThrows
testClientProxyNegativePortThrows
testClientProxyNullHostThrows
testClientProxyNullThrows
testClientValidProxyDoesNotThrow
testError
2020-08-03 11:19:08.263 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:08.266 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@52ca0ad4{/,null,AVAILABLE}
2020-08-03 11:19:08.267 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@ce561cc{HTTP/1.1,[http/1.1]}{0.0.0.0:41319}
2020-08-03 11:19:08.267 INFO  org.eclipse.jetty.server.Server - Started @3951ms
2020-08-03 11:19:08.279 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@ce561cc{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:08.280 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@52ca0ad4{/,null,UNAVAILABLE}
testFlowableFactoryThrows
2020-08-03 11:19:08.282 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:08.285 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@738a815c{/,null,AVAILABLE}
2020-08-03 11:19:08.286 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@35dcd032{HTTP/1.1,[http/1.1]}{0.0.0.0:46509}
2020-08-03 11:19:08.286 INFO  org.eclipse.jetty.server.Server - Started @3970ms
2020-08-03 11:19:08.305 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@35dcd032{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:08.306 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@738a815c{/,null,UNAVAILABLE}
testGetAsynchronousSource
2020-08-03 11:19:08.309 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:08.311 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@3a16984c{/,null,AVAILABLE}
2020-08-03 11:19:08.312 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@15c16f19{HTTP/1.1,[http/1.1]}{0.0.0.0:41655}
2020-08-03 11:19:08.312 INFO  org.eclipse.jetty.server.Server - Started @3997ms
2020-08-03 11:19:08.630 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@15c16f19{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:08.630 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@3a16984c{/,null,UNAVAILABLE}
testGetEmptyStream
2020-08-03 11:19:08.632 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:08.634 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@6aad919c{/,null,AVAILABLE}
2020-08-03 11:19:08.635 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@3a3ad8e7{HTTP/1.1,[http/1.1]}{0.0.0.0:34507}
2020-08-03 11:19:08.636 INFO  org.eclipse.jetty.server.Server - Started @4319ms
2020-08-03 11:19:08.646 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@3a3ad8e7{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:08.646 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@6aad919c{/,null,UNAVAILABLE}
testGetWithClient
2020-08-03 11:19:08.648 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:08.653 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@4efb13f1{/,null,AVAILABLE}
2020-08-03 11:19:08.655 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@211a9647{HTTP/1.1,[http/1.1]}{0.0.0.0:41039}
2020-08-03 11:19:08.655 INFO  org.eclipse.jetty.server.Server - Started @4339ms
java.nio.HeapByteBuffer[pos=0 lim=3 cap=3]
java.nio.HeapByteBuffer[pos=0 lim=4 cap=4]
2020-08-03 11:19:08.671 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@211a9647{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:08.671 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@4efb13f1{/,null,UNAVAILABLE}
testGetWithClient2
2020-08-03 11:19:08.673 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:08.675 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@65d73bd{/,null,AVAILABLE}
2020-08-03 11:19:08.676 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@7d284f15{HTTP/1.1,[http/1.1]}{0.0.0.0:45785}
2020-08-03 11:19:08.677 INFO  org.eclipse.jetty.server.Server - Started @4361ms
2020-08-03 11:19:08.689 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@7d284f15{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:08.689 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@65d73bd{/,null,UNAVAILABLE}
testGetWithClientHttpPost
2020-08-03 11:19:08.691 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:08.693 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@45d7495e{/,null,AVAILABLE}
2020-08-03 11:19:08.695 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@6f3b13d0{HTTP/1.1,[http/1.1]}{0.0.0.0:36933}
2020-08-03 11:19:08.695 INFO  org.eclipse.jetty.server.Server - Started @4379ms
2020-08-03 11:19:08.705 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@6f3b13d0{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:08.706 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@45d7495e{/,null,UNAVAILABLE}
testLongByteArrayStream
2020-08-03 11:19:08.708 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:08.710 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@6e239337{/,null,AVAILABLE}
2020-08-03 11:19:08.716 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@79ad1774{HTTP/1.1,[http/1.1]}{0.0.0.0:32991}
2020-08-03 11:19:08.717 INFO  org.eclipse.jetty.server.Server - Started @4401ms
0s:1
numBytes=131072, 10224 items/s, 1278.000MB/s
2020-08-03 11:19:09.696 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@79ad1774{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:09.697 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@6e239337{/,null,UNAVAILABLE}
testLongStream
2020-08-03 11:19:09.700 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:09.702 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@52a67293{/,null,AVAILABLE}
2020-08-03 11:19:09.704 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@300bb303{HTTP/1.1,[http/1.1]}{0.0.0.0:46007}
2020-08-03 11:19:09.704 INFO  org.eclipse.jetty.server.Server - Started @5388ms
0s:1
0s:100001
0s:200001
1s:300001
1s:400001
2s:500001
2s:600001
3s:700001
3s:800001
4s:900001
4s:1000001
225479 items/s
2020-08-03 11:19:14.140 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@300bb303{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:14.140 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@52a67293{/,null,UNAVAILABLE}
testRangeAsync
2020-08-03 11:19:14.141 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:14.142 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@ff03361{/,null,AVAILABLE}
2020-08-03 11:19:14.142 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@36f6d25c{HTTP/1.1,[http/1.1]}{0.0.0.0:38307}
2020-08-03 11:19:14.143 INFO  org.eclipse.jetty.server.Server - Started @9827ms
9223372036854775807
500
2020-08-03 11:19:14.256 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@36f6d25c{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:14.257 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@ff03361{/,null,UNAVAILABLE}
testRangeManyTimes
2020-08-03 11:19:14.259 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:14.261 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@34ab26a{/,null,AVAILABLE}
2020-08-03 11:19:14.263 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@9c0d0bd{HTTP/1.1,[http/1.1]}{0.0.0.0:39017}
2020-08-03 11:19:14.263 INFO  org.eclipse.jetty.server.Server - Started @9947ms
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | org.eclipse.jetty.io.EofException
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.doOnComplete(Server.java:220)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.drain(Server.java:196)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.onComplete(Server.java:149)
	at io.reactivex.internal.util.HalfSerializer.onComplete(HalfSerializer.java:90)
	at io.reactivex.internal.subscribers.StrictSubscriber.onComplete(StrictSubscriber.java:109)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120)
	at io.reactivex.internal.operators.flowable.FlowableRange$RangeSubscription.fastPath(FlowableRange.java:133)
	at io.reactivex.internal.operators.flowable.FlowableRange$BaseRangeSubscription.request(FlowableRange.java:90)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredRequest(SubscriptionHelper.java:219)
	at io.reactivex.internal.subscribers.StrictSubscriber.request(StrictSubscriber.java:70)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.lambda$request$0(Server.java:118)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:284)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:820)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:550)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:850)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:921)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:249)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:225)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:407)
	at org.davidmoten.rx2.http.Writer$1.flush(Writer.java:45)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.doOnComplete(Server.java:218)
	... 19 more
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:264)
	... 33 more
Exception in thread "RxCachedThreadScheduler-62" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | org.eclipse.jetty.io.EofException
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.doOnComplete(Server.java:220)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.drain(Server.java:196)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.onComplete(Server.java:149)
	at io.reactivex.internal.util.HalfSerializer.onComplete(HalfSerializer.java:90)
	at io.reactivex.internal.subscribers.StrictSubscriber.onComplete(StrictSubscriber.java:109)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120)
	at io.reactivex.internal.operators.flowable.FlowableRange$RangeSubscription.fastPath(FlowableRange.java:133)
	at io.reactivex.internal.operators.flowable.FlowableRange$BaseRangeSubscription.request(FlowableRange.java:90)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredRequest(SubscriptionHelper.java:219)
	at io.reactivex.internal.subscribers.StrictSubscriber.request(StrictSubscriber.java:70)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.lambda$request$0(Server.java:118)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:284)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:820)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:550)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:850)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:921)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:249)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:225)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:407)
	at org.davidmoten.rx2.http.Writer$1.flush(Writer.java:45)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.doOnComplete(Server.java:218)
	... 19 more
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:264)
	... 33 more
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | org.eclipse.jetty.io.EofException
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.doOnComplete(Server.java:220)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.drain(Server.java:196)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.onComplete(Server.java:149)
	at io.reactivex.internal.util.HalfSerializer.onComplete(HalfSerializer.java:90)
	at io.reactivex.internal.subscribers.StrictSubscriber.onComplete(StrictSubscriber.java:109)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120)
	at io.reactivex.internal.operators.flowable.FlowableRange$RangeSubscription.fastPath(FlowableRange.java:133)
	at io.reactivex.internal.operators.flowable.FlowableRange$BaseRangeSubscription.request(FlowableRange.java:90)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredRequest(SubscriptionHelper.java:219)
	at io.reactivex.internal.subscribers.StrictSubscriber.request(StrictSubscriber.java:70)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.lambda$request$0(Server.java:118)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:284)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:820)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:550)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:850)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:921)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:249)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:225)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:407)
	at org.davidmoten.rx2.http.Writer$1.flush(Writer.java:45)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.doOnComplete(Server.java:218)
	... 19 more
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:264)
	... 33 more
Exception in thread "RxCachedThreadScheduler-67" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | org.eclipse.jetty.io.EofException
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.doOnComplete(Server.java:220)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.drain(Server.java:196)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.onComplete(Server.java:149)
	at io.reactivex.internal.util.HalfSerializer.onComplete(HalfSerializer.java:90)
	at io.reactivex.internal.subscribers.StrictSubscriber.onComplete(StrictSubscriber.java:109)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120)
	at io.reactivex.internal.operators.flowable.FlowableRange$RangeSubscription.fastPath(FlowableRange.java:133)
	at io.reactivex.internal.operators.flowable.FlowableRange$BaseRangeSubscription.request(FlowableRange.java:90)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredRequest(SubscriptionHelper.java:219)
	at io.reactivex.internal.subscribers.StrictSubscriber.request(StrictSubscriber.java:70)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.lambda$request$0(Server.java:118)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:284)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:820)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:550)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:850)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:921)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:249)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:225)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:407)
	at org.davidmoten.rx2.http.Writer$1.flush(Writer.java:45)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.doOnComplete(Server.java:218)
	... 19 more
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:264)
	... 33 more
2020-08-03 11:19:21.048 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@9c0d0bd{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:21.049 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@34ab26a{/,null,UNAVAILABLE}
testRangeParallel
2020-08-03 11:19:21.050 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:21.051 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@ee2ae9a{/,null,AVAILABLE}
2020-08-03 11:19:21.052 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@6cd45b6c{HTTP/1.1,[http/1.1]}{0.0.0.0:42085}
2020-08-03 11:19:21.052 INFO  org.eclipse.jetty.server.Server - Started @16736ms
2020-08-03 11:19:21.071 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@6cd45b6c{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:21.071 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@ee2ae9a{/,null,UNAVAILABLE}
testRangeParallelLongRunning
2020-08-03 11:19:21.072 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:21.073 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@d66502{/,null,AVAILABLE}
2020-08-03 11:19:21.074 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@55044b34{HTTP/1.1,[http/1.1]}{0.0.0.0:44227}
2020-08-03 11:19:21.074 INFO  org.eclipse.jetty.server.Server - Started @16758ms
2020-08-03 11:19:23.760 INFO  org.davidmoten.rx2.io.ClientTest - count=100000
2020-08-03 11:19:23.762 INFO  org.davidmoten.rx2.io.ClientTest - count=100000
2020-08-03 11:19:23.764 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@55044b34{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:23.765 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@d66502{/,null,UNAVAILABLE}
testRangeParallelSync
2020-08-03 11:19:23.766 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:23.767 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@79604abe{/,null,AVAILABLE}
2020-08-03 11:19:23.768 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@5d08976a{HTTP/1.1,[http/1.1]}{0.0.0.0:37905}
2020-08-03 11:19:23.768 INFO  org.eclipse.jetty.server.Server - Started @19452ms
2020-08-03 11:19:23.788 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@5d08976a{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:23.789 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@79604abe{/,null,UNAVAILABLE}
testRangeRebatchedManyTimes
2020-08-03 11:19:23.790 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:23.791 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@77bb916f{/,null,AVAILABLE}
2020-08-03 11:19:23.792 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@7e81617a{HTTP/1.1,[http/1.1]}{0.0.0.0:41195}
2020-08-03 11:19:23.792 INFO  org.eclipse.jetty.server.Server - Started @19476ms
2020-08-03 11:19:24.324 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@7e81617a{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:24.325 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@77bb916f{/,null,UNAVAILABLE}
testRequestHeaderNullThrows
testRequestHeaderNullValueThrows
testRequestOfUnknownStreamIdShouldEmitError
2020-08-03 11:19:24.327 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:24.329 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@402d6012{/,null,AVAILABLE}
2020-08-03 11:19:24.330 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@521ba38f{HTTP/1.1,[http/1.1]}{0.0.0.0:46579}
2020-08-03 11:19:24.330 INFO  org.eclipse.jetty.server.Server - Started @20014ms
2020-08-03 11:19:24.331 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@521ba38f{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:24.331 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@402d6012{/,null,UNAVAILABLE}
testRequesterNon200ResponseCode
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.ConnectException: Connection refused (Connection refused)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.Client$Requester.lambda$accept$0(Client.java:370)
	at io.reactivex.internal.schedulers.TrampolineScheduler.scheduleDirect(TrampolineScheduler.java:52)
	at org.davidmoten.rx2.io.Client$Requester.accept(Client.java:358)
	at org.davidmoten.rx2.io.ClientTest.testRequesterNon200ResponseCode(ClientTest.java:633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.davidmoten.rx2.io.Client$Requester.lambda$accept$0(Client.java:364)
	... 27 more
Exception in thread "main" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.ConnectException: Connection refused (Connection refused)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.Client$Requester.lambda$accept$0(Client.java:370)
	at io.reactivex.internal.schedulers.TrampolineScheduler.scheduleDirect(TrampolineScheduler.java:52)
	at org.davidmoten.rx2.io.Client$Requester.accept(Client.java:358)
	at org.davidmoten.rx2.io.ClientTest.testRequesterNon200ResponseCode(ClientTest.java:633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.davidmoten.rx2.io.Client$Requester.lambda$accept$0(Client.java:364)
	... 27 more
testSimpleGet
2020-08-03 11:19:24.337 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:24.340 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@70f4abc1{/,null,AVAILABLE}
2020-08-03 11:19:24.341 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@1573e8a5{HTTP/1.1,[http/1.1]}{0.0.0.0:44171}
2020-08-03 11:19:24.341 INFO  org.eclipse.jetty.server.Server - Started @20025ms
[57, -120, 97, -80, -66, 17, 51, -49, 0, 0, 0, 3, 1, 2, 3, 0, 0, 0, 4, 4, 5, 6, 7, -128, 0, 0, 0]
2020-08-03 11:19:24.345 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@1573e8a5{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:24.345 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@70f4abc1{/,null,UNAVAILABLE}
testStreamWithEmptyByteBuffer
2020-08-03 11:19:24.347 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:24.349 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@5d84e363{/,null,AVAILABLE}
2020-08-03 11:19:24.350 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@a2df0d5{HTTP/1.1,[http/1.1]}{0.0.0.0:33397}
2020-08-03 11:19:24.350 INFO  org.eclipse.jetty.server.Server - Started @20034ms
2020-08-03 11:19:24.357 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@a2df0d5{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:24.357 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@5d84e363{/,null,UNAVAILABLE}
testStreamWithEmptyByteBufferThenMore
2020-08-03 11:19:24.386 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:24.387 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@2a120c88{/,null,AVAILABLE}
2020-08-03 11:19:24.388 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@2bf3ec4{HTTP/1.1,[http/1.1]}{0.0.0.0:34367}
2020-08-03 11:19:24.388 INFO  org.eclipse.jetty.server.Server - Started @20073ms
2020-08-03 11:19:24.394 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@2bf3ec4{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:24.394 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@2a120c88{/,null,UNAVAILABLE}
testValuesThenError
2020-08-03 11:19:24.395 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:24.397 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@13908f9c{/,null,AVAILABLE}
2020-08-03 11:19:24.398 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@7ab2ba47{HTTP/1.1,[http/1.1]}{0.0.0.0:33041}
2020-08-03 11:19:24.398 INFO  org.eclipse.jetty.server.Server - Started @20082ms
2020-08-03 11:19:24.407 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@7ab2ba47{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2020-08-03 11:19:24.408 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@13908f9c{/,null,UNAVAILABLE}
Tests run: 37, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.653 sec - in org.davidmoten.rx2.io.ClientTest
Running org.davidmoten.rx2.io.ByteBufferInputStreamTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.davidmoten.rx2.io.ByteBufferInputStreamTest
Running org.davidmoten.rx2.io.ClientSslTest
2020-08-03 11:19:24.554 INFO  org.eclipse.jetty.server.Server - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_262-b10
2020-08-03 11:19:24.560 INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@41f686af{/,null,AVAILABLE}
2020-08-03 11:19:24.564 INFO  org.eclipse.jetty.util.ssl.SslContextFactory - x509=X509@26d8908e(testing,h=[testing.com],w=[]) for SslContextFactory@30e2016a[provider=null,keyStore=file:///tmp/tmp08_viptj/rxjava2-http/target/test-classes/keyStore.jks,trustStore=null]
2020-08-03 11:19:24.578 INFO  org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@341ccfd1{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2020-08-03 11:19:24.578 INFO  org.eclipse.jetty.server.Server - Started @20263ms
2020-08-03 11:19:24.998 INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@341ccfd1{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2020-08-03 11:19:24.999 INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@41f686af{/,null,UNAVAILABLE}
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.572 sec - in org.davidmoten.rx2.io.ClientSslTest
Running org.davidmoten.rx2.io.internal.FlowableFromInputStreamTest
emitting error boo
emitting error always throw
emitting error null
emitting error always throw
emitting error encountered EOF before expected length was read
emitting error always throw
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.RuntimeException: will appear in RxJavaPlugins onError output
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.internal.FlowableFromInputStream$FromStreamSubscription.cancelUpstream(FlowableFromInputStream.java:285)
	at org.davidmoten.rx2.io.internal.FlowableFromInputStream$FromStreamSubscription.cancel(FlowableFromInputStream.java:271)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:181)
	at io.reactivex.subscribers.TestSubscriber.cancel(TestSubscriber.java:268)
	at org.davidmoten.rx2.io.internal.FlowableFromInputStreamTest.testRequesterFailsOnCancel(FlowableFromInputStreamTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.RuntimeException: will appear in RxJavaPlugins onError output
	at org.davidmoten.rx2.io.internal.FlowableFromInputStreamTest.lambda$testRequesterFailsOnCancel$2(FlowableFromInputStreamTest.java:51)
	at org.davidmoten.rx2.io.internal.FlowableFromInputStream$FromStreamSubscription.cancelUpstream(FlowableFromInputStream.java:282)
	... 28 more
Exception in thread "main" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.RuntimeException: will appear in RxJavaPlugins onError output
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.internal.FlowableFromInputStream$FromStreamSubscription.cancelUpstream(FlowableFromInputStream.java:285)
	at org.davidmoten.rx2.io.internal.FlowableFromInputStream$FromStreamSubscription.cancel(FlowableFromInputStream.java:271)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:181)
	at io.reactivex.subscribers.TestSubscriber.cancel(TestSubscriber.java:268)
	at org.davidmoten.rx2.io.internal.FlowableFromInputStreamTest.testRequesterFailsOnCancel(FlowableFromInputStreamTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.RuntimeException: will appear in RxJavaPlugins onError output
	at org.davidmoten.rx2.io.internal.FlowableFromInputStreamTest.lambda$testRequesterFailsOnCancel$2(FlowableFromInputStreamTest.java:51)
	at org.davidmoten.rx2.io.internal.FlowableFromInputStream$FromStreamSubscription.cancelUpstream(FlowableFromInputStream.java:282)
	... 28 more
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec - in org.davidmoten.rx2.io.internal.FlowableFromInputStreamTest
Running org.davidmoten.rx2.io.internal.HandlerTest
[0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 12, -128, 0, 0, 0]
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.davidmoten.rx2.io.internal.HandlerTest
Running org.davidmoten.rx2.io.internal.UtilTest
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.io.IOException
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.internal.Util.close(Util.java:69)
	at org.davidmoten.rx2.io.internal.UtilTest.testCloseThrowingDoesNotThrow(UtilTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.io.IOException
	at org.davidmoten.rx2.io.internal.UtilTest$1.close(UtilTest.java:37)
	at org.davidmoten.rx2.io.internal.Util.close(Util.java:67)
	... 25 more
Exception in thread "main" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.io.IOException
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.internal.Util.close(Util.java:69)
	at org.davidmoten.rx2.io.internal.UtilTest.testCloseThrowingDoesNotThrow(UtilTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.io.IOException
	at org.davidmoten.rx2.io.internal.UtilTest$1.close(UtilTest.java:37)
	at org.davidmoten.rx2.io.internal.Util.close(Util.java:67)
	... 25 more
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in org.davidmoten.rx2.io.internal.UtilTest
Running org.davidmoten.rx2.io.internal.DefaultSerializerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.davidmoten.rx2.io.internal.DefaultSerializerTest
Running org.davidmoten.rx2.io.internal.ServletHandlerTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.133 sec - in org.davidmoten.rx2.io.internal.ServletHandlerTest
Running org.davidmoten.rx2.io.internal.FlowableSingleFlatMapPublisherTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.005 sec - in org.davidmoten.rx2.io.internal.FlowableSingleFlatMapPublisherTest
Running org.davidmoten.rx2.io.internal.ServerTest
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.io.IOException
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.writeError(Server.java:240)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.drain(Server.java:191)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.onSuccess(Server.java:110)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.onSuccess(Server.java:52)
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.onSubscribe(Server.java:89)
	at io.reactivex.internal.subscribers.StrictSubscriber.onSubscribe(StrictSubscriber.java:85)
	at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14885)
	at org.davidmoten.rx2.io.internal.Server.handle(Server.java:49)
	at org.davidmoten.rx2.io.internal.ServerTest.handleOutputStreamThrowsWritingId(ServerTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.io.IOException
	at org.davidmoten.rx2.io.internal.ServerTest$1.write(ServerTest.java:33)
	at org.davidmoten.rx2.http.Writer$1.write(Writer.java:40)
	at org.davidmoten.rx2.io.internal.Server.writeInt(Server.java:262)
	at org.davidmoten.rx2.io.internal.Server.access$000(Server.java:30)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.writeError(Server.java:233)
	... 36 more
Exception in thread "main" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.io.IOException
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.writeError(Server.java:240)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.drain(Server.java:191)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.onSuccess(Server.java:110)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.onSuccess(Server.java:52)
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.onSubscribe(Server.java:89)
	at io.reactivex.internal.subscribers.StrictSubscriber.onSubscribe(StrictSubscriber.java:85)
	at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14885)
	at org.davidmoten.rx2.io.internal.Server.handle(Server.java:49)
	at org.davidmoten.rx2.io.internal.ServerTest.handleOutputStreamThrowsWritingId(ServerTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.io.IOException
	at org.davidmoten.rx2.io.internal.ServerTest$1.write(ServerTest.java:33)
	at org.davidmoten.rx2.http.Writer$1.write(Writer.java:40)
	at org.davidmoten.rx2.io.internal.Server.writeInt(Server.java:262)
	at org.davidmoten.rx2.io.internal.Server.access$000(Server.java:30)
	at org.davidmoten.rx2.io.internal.Server$HandlerSubscriber.writeError(Server.java:233)
	... 36 more
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 sec - in org.davidmoten.rx2.io.internal.ServerTest

Results :

Tests run: 72, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.5:report (report) @ rxjava2-http ---
[INFO] Loading execution data file /tmp/tmp08_viptj/rxjava2-http/target/jacoco.exec
[INFO] Analyzed bundle 'rxjava2-http' with 37 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  48.603 s
[INFO] Finished at: 2020-08-03T11:19:26Z
[INFO] ------------------------------------------------------------------------
