[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< io.vertx:vertx-unit >-------------------------
[INFO] Building Vert.x Unit 3.5.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ vertx-unit ---
[INFO] 
[INFO] --- maven-processor-plugin:3.2.0:process (generate-sources) @ vertx-unit ---
INFO: io.vertx.codegen.CodeGenProcessor - Loaded data_object_converters code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded Groovy code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded Groovy code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded Groovy code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded JavaScript code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded Ruby code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded RxJava code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded RxJava2 code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded Kotlin code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded cheatsheet code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Loaded cheatsheet code generator 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestSuite: io.vertx.rxjava.ext.unit.TestSuite 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.collect.EventBusCollector: io.vertx.reactivex.ext.unit.collect.EventBusCollector 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.Completion: io.vertx.groovy.ext.unit.Completion_GroovyExtension 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.collect.EventBusCollector: io.vertx.rxjava.ext.unit.collect.EventBusCollector 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.Async: io.vertx.rxjava.ext.unit.Async 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestContext: io.vertx.rxjava.ext.unit.TestContext 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestResult: io.vertx.reactivex.ext.unit.report.TestResult 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.collect.EventBusCollector: io.vertx.groovy.ext.unit.collect.EventBusCollector_GroovyStaticExtension 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestSuiteReport: io.vertx.reactivex.ext.unit.report.TestSuiteReport 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.Failure: io.vertx.reactivex.ext.unit.report.Failure 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestSuite: io.vertx.reactivex.ext.unit.TestSuite 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestCompletion: io.vertx.reactivex.ext.unit.TestCompletion 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestCase: io.vertx.rxjava.ext.unit.TestCase 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestContext: io.vertx.groovy.ext.unit.TestContext_GroovyExtension 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestSuiteReport: io.vertx.rxjava.ext.unit.report.TestSuiteReport 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestCompletion: io.vertx.rxjava.ext.unit.TestCompletion 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestCaseReport: io.vertx.reactivex.ext.unit.report.TestCaseReport 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestSuite: io.vertx.groovy.ext.unit.TestSuite_GroovyExtension 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestContext: io.vertx.reactivex.ext.unit.TestContext 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestCaseReport: io.vertx.rxjava.ext.unit.report.TestCaseReport 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.Failure: io.vertx.rxjava.ext.unit.report.Failure 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.Async: io.vertx.groovy.ext.unit.VertxExtensionModule 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.Completion: io.vertx.rxjava.ext.unit.Completion 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.Async: io.vertx.reactivex.ext.unit.Async 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestCase: io.vertx.reactivex.ext.unit.TestCase 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestResult: io.vertx.rxjava.ext.unit.report.TestResult 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.Completion: io.vertx.reactivex.ext.unit.Completion 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.Failure: vertx-unit-js/failure.js 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestCompletion: vertx-unit/test_completion.rb 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestCase: vertx-unit-js/test_case.js 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestResult: vertx-unit/test_result.rb 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestResult: vertx-unit-js/test_result.js 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestSuite: vertx-unit-js/test_suite.js 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestContext: vertx-unit/test_context.rb 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.Async: vertx-unit-js/async.js 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestSuiteReport: vertx-unit-js/test_suite_report.js 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.Failure: vertx-unit/failure.rb 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.collect.EventBusCollector: vertx-unit/event_bus_collector.rb 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestCaseReport: vertx-unit/test_case_report.rb 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestCase: vertx-unit/test_case.rb 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.collect.EventBusCollector: vertx-unit-js/event_bus_collector.js 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestSuiteReport: vertx-unit/test_suite_report.rb 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestContext: vertx-unit-js/test_context.js 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestCompletion: vertx-unit-js/test_completion.js 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.Completion: vertx-unit/completion.rb 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.TestCaseReport: vertx-unit-js/test_case_report.js 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.Async: vertx-unit/async.rb 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.Completion: vertx-unit-js/completion.js 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestSuite: vertx-unit/test_suite.rb 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.ReportingOptions: kotlin/io/vertx/kotlin/ext/unit/report/ReportingOptions.kt 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.ReportOptions: generated/io/vertx/ext/unit/report/ReportOptionsConverter.java 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.ReportOptions: asciidoc/dataobjects.adoc 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestOptions: generated/io/vertx/ext/unit/TestOptionsConverter.java 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.TestOptions: kotlin/io/vertx/kotlin/ext/unit/TestOptions.kt 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.ReportOptions: kotlin/io/vertx/kotlin/ext/unit/report/ReportOptions.kt 
INFO: io.vertx.codegen.CodeGenProcessor - Generated model io.vertx.ext.unit.report.ReportingOptions: generated/io/vertx/ext/unit/report/ReportingOptionsConverter.java 
[WARNING] diagnostic: warning: The following options were not recognized by any processor: '[maven.artifactId, maven.version, codegen.output.data_object_converters, codegen.rxjava.deprecated, maven.groupId]'
[INFO] 
[INFO] --- build-helper-maven-plugin:1.12:add-source (add-source) @ vertx-unit ---
[INFO] Source directory: /tmp/tmpw9yka2ur/vertx-unit/src/main/generated added.
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ vertx-unit ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 89 source files to /tmp/tmpw9yka2ur/vertx-unit/target/classes
[WARNING] /tmp/tmpw9yka2ur/vertx-unit/src/main/java/io/vertx/ext/unit/report/impl/JunitXmlFormatter.java: Some input files use or override a deprecated API.
[WARNING] /tmp/tmpw9yka2ur/vertx-unit/src/main/java/io/vertx/ext/unit/report/impl/JunitXmlFormatter.java: Recompile with -Xlint:deprecation for details.
[WARNING] /tmp/tmpw9yka2ur/vertx-unit/target/generated-sources/annotations/io/vertx/reactivex/ext/unit/Completion.java: Some input files use unchecked or unsafe operations.
[WARNING] /tmp/tmpw9yka2ur/vertx-unit/target/generated-sources/annotations/io/vertx/reactivex/ext/unit/Completion.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- gmavenplus-plugin:1.5:compile (default) @ vertx-unit ---
[INFO] No sources specified for compilation.  Skipping.
[INFO] 
[INFO] --- kotlin-maven-plugin:1.2.20:compile (default) @ vertx-unit ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ vertx-unit ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- bnd-maven-plugin:3.2.0:bnd-process (default-bnd-process) @ vertx-unit ---
[WARNING] /tmp/tmpw9yka2ur/vertx-unit/pom.xml [0:0]: Unused Import-Package instructions: [io.vertx.groovy.*, io.vertx.ext.auth.*, io.vertx.lang.groovy.*, io.vertx.rxjava.ext.auth.*] 
[WARNING] /tmp/tmpw9yka2ur/vertx-unit/pom.xml [0:0]: Invalid package name: 'vertx-unit'
[WARNING] /tmp/tmpw9yka2ur/vertx-unit/pom.xml [0:0]: Invalid package name: 'vertx-unit-js'
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ vertx-unit ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 12 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ vertx-unit ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 20 source files to /tmp/tmpw9yka2ur/vertx-unit/target/test-classes
[WARNING] /tmp/tmpw9yka2ur/vertx-unit/src/test/java/io/vertx/ext/unit/JunitXmlReporterTest.java: /tmp/tmpw9yka2ur/vertx-unit/src/test/java/io/vertx/ext/unit/JunitXmlReporterTest.java uses or overrides a deprecated API.
[WARNING] /tmp/tmpw9yka2ur/vertx-unit/src/test/java/io/vertx/ext/unit/JunitXmlReporterTest.java: Recompile with -Xlint:deprecation for details.
[WARNING] /tmp/tmpw9yka2ur/vertx-unit/src/test/java/io/vertx/ext/unit/JUnitParameterizedTest.java: /tmp/tmpw9yka2ur/vertx-unit/src/test/java/io/vertx/ext/unit/JUnitParameterizedTest.java uses unchecked or unsafe operations.
[WARNING] /tmp/tmpw9yka2ur/vertx-unit/src/test/java/io/vertx/ext/unit/JUnitParameterizedTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- gmavenplus-plugin:1.5:testCompile (default) @ vertx-unit ---
[INFO] Using Groovy 2.4.7 to perform testCompile.
[INFO] Compiled 3 files.
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ vertx-unit ---
[INFO] Surefire report directory: /tmp/tmpw9yka2ur/vertx-unit/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.vertx.test.unit.GroovyJUnitTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in io.vertx.test.unit.GroovyJUnitTest
Running io.vertx.test.unit.GroovyJUnitParameterizedTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.199 sec - in io.vertx.test.unit.GroovyJUnitParameterizedTest
Running io.vertx.ext.unit.ReportingTest
Starting test: ReportingTest#testReportWithDefaultOptions 
Starting test: ReportingTest#testReportToLog 
Begin test suite my_suite
 
Begin test my_test
 
Passed my_test
 
End test suite my_suite , run: 1, Failures: 0, Errors: 0
 
Starting test: ReportingTest#testReportSucceededToCompletionHandler 
Starting test: ReportingTest#testReportToConsole 
Starting test: ReportingTest#testJunitFormatReporter 
Starting test: ReportingTest#testReportToFailureCompletionHandler 
Starting test: ReportingTest#testReportToEventBus 
Starting test: ReportingTest#testSimpleFormatReporter 
Starting test: ReportingTest#testReportToFile 
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.876 sec - in io.vertx.ext.unit.ReportingTest
Running io.vertx.ext.unit.EventBusTest
Starting test: EventBusTest#testEndToEnd 
Starting test: EventBusTest#testEndToEndAfterFailure 
Starting test: EventBusTest#testEventBusReporter 
Starting test: EventBusTest#testEventBusReportAfterFailure 
Starting test: EventBusTest#testEventBusReporterTestSuiteFailure 
Starting test: EventBusTest#testEventBusReport 
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.194 sec - in io.vertx.ext.unit.EventBusTest
Running io.vertx.ext.unit.OptionsTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in io.vertx.ext.unit.OptionsTest
Running io.vertx.ext.unit.JunitXmlReporterTest
Starting test: JunitXmlReporterTest#testReportTestCases 
Starting test: JunitXmlReporterTest#testReportBeforeFailure 
Starting test: JunitXmlReporterTest#testReportAfterFailure 
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.094 sec - in io.vertx.ext.unit.JunitXmlReporterTest
Running io.vertx.ext.unit.VerticleTest
Starting test: VerticleTest#testCoordinated 
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.851 sec - in io.vertx.ext.unit.VerticleTest
Running io.vertx.ext.unit.TestSuiteNoEventLoopAsyncTest
Tests run: 40, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.865 sec <<< FAILURE! - in io.vertx.ext.unit.TestSuiteNoEventLoopAsyncTest
runTestWithAsyncCompletionAfterFailureInTest(io.vertx.ext.unit.TestSuiteNoEventLoopAsyncTest)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.vertx.ext.unit.TestSuiteTestBase.runTestWithAsyncCompletionAfterFailureInTest(TestSuiteTestBase.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running io.vertx.ext.unit.TestSuiteNoEventLoopWithVertxTest
Tests run: 40, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.563 sec - in io.vertx.ext.unit.TestSuiteNoEventLoopWithVertxTest
Running io.vertx.ext.unit.TestSuiteNoEventLoopTest
Tests run: 40, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.791 sec - in io.vertx.ext.unit.TestSuiteNoEventLoopTest
Running io.vertx.ext.unit.TestSuiteUseContextualEventLoopTest
Tests run: 40, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.571 sec - in io.vertx.ext.unit.TestSuiteUseContextualEventLoopTest
Running io.vertx.ext.unit.CompletionTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.243 sec - in io.vertx.ext.unit.CompletionTest
Running io.vertx.ext.unit.ExamplesTest
------ begin example 2
Begin test suite the_test_suite
Begin test my_test_case
Passed my_test_case
End test suite the_test_suite , run: 1, Failures: 0, Errors: 0
------ end example 2
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in io.vertx.ext.unit.ExamplesTest
Running io.vertx.ext.unit.TestSuiteObjectTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in io.vertx.ext.unit.TestSuiteObjectTest
Running io.vertx.ext.unit.TestSuiteUseVertxEventLoopTest
Tests run: 40, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.625 sec - in io.vertx.ext.unit.TestSuiteUseVertxEventLoopTest
Running io.vertx.ext.unit.UseEventLoopTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in io.vertx.ext.unit.UseEventLoopTest
Running io.vertx.ext.unit.JUnitTestSuiteTest
before
beforeEach
testSomethingElse
afterEach
beforeEach
testSomething
afterEach
after
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in io.vertx.ext.unit.JUnitTestSuiteTest
Running io.vertx.ext.unit.JUnitParameterizedTest
Exception in thread "Thread-419" java.lang.AssertionError: Test failed
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:467)
	at io.vertx.ext.unit.impl.TestContextImpl.fail(TestContextImpl.java:335)
	at io.vertx.ext.unit.impl.TestContextImpl.fail(TestContextImpl.java:331)
	at io.vertx.ext.unit.JUnitParameterizedTest$SimpleParameterizedTestSuite$1.run(JUnitParameterizedTest.java:52)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.406 sec - in io.vertx.ext.unit.JUnitParameterizedTest
Running io.vertx.ext.unit.LangTest
Starting test: LangTest#testRubyFailure 
Unhandled exception 
org.jruby.exceptions.RaiseException: (Exception) the_failure
	at RUBY.block in to_throwable(uri:classloader:/vertx/util/utils.rb:19)
	at RUBY.to_throwable(uri:classloader:/vertx/util/utils.rb:19)
	at RUBY.fail(uri:classloader:/vertx-unit/test_context.rb:199)
	at RUBY.block in vertx_start_async(failing.rb:8)
	at RUBY.block in set_timer(uri:classloader:/vertx/vertx.rb:228)

Starting test: LangTest#testGroovyFailure 
Unhandled exception 
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy49.handle(Unknown Source)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: the_failure
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at verticle.failing$_vertxStart_closure1$_closure2.doCall(failing.groovy:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	... 10 more

Starting test: LangTest#testAssertionsRuby 
Starting test: LangTest#testJavaScriptTimer 
Starting test: LangTest#testGroovyExceptionHandler 
Unhandled exception 
java.lang.AssertionError: the_failure
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at verticle.exceptionHandler$_vertxStart_closure2$_closure3.doCall(exceptionHandler.groovy:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	at com.sun.proxy.$Proxy49.handle(Unknown Source)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Starting test: LangTest#testGroovyTimer 
Starting test: LangTest#testJavaScriptFailure 
Unhandled exception 
<eval>#88:17<eval>:55:4 Error: the_failure
	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:102)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:106)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:110)
	at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)
	at jdk.nashorn.internal.scripts.Script$Recompilation$527$334A$\^eval\_#88\!17\^eval\_.L:1#vertxStartAsync#suite#L:5(src/test/resources/verticle/failing.js:6)
	at jdk.nashorn.internal.scripts.Script$Recompilation$525$10647A$\^eval\_#88\!17\^eval\_.L:1#Vertx#setTimer#L:263(.vertx/debug-js/vertx-js/vertx.js:264)
	at io.vertx.core.Handler$$NashornJavaAdapter.handle(Unknown Source)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Starting test: LangTest#testAssertionsJs 
Starting test: LangTest#testGroovy 
Starting test: LangTest#testAssertionsGroovy 
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.301 sec - in io.vertx.ext.unit.LangTest
Running io.vertx.ext.unit.JUnitTest
Unhandled exception 
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at io.vertx.ext.unit.JUnitTest$FailOnContext.lambda$testMethod1$0(JUnitTest.java:955)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Unhandled exception 
java.lang.AssertionError: Don't freak out
	at org.junit.Assert.fail(Assert.java:88)
	at io.vertx.ext.unit.JUnitTest$HttpRequestFailure.lambda$before$0(JUnitTest.java:1015)
	at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:433)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:141)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:683)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:636)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.HttpServerImpl$Http2UpgradeHandler.channelRead(HttpServerImpl.java:952)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:60)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

io.vertx.core.VertxException: Connection was closed 
*** Iteration 1/3 of test testMethod(io.vertx.ext.unit.JUnitTest$RepeatRuleTestSuite)
*** Iteration 2/3 of test testMethod(io.vertx.ext.unit.JUnitTest$RepeatRuleTestSuite)
*** Iteration 3/3 of test testMethod(io.vertx.ext.unit.JUnitTest$RepeatRuleTestSuite)
Exception in thread "Thread-711" java.lang.AssertionError: expected
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:467)
	at io.vertx.ext.unit.impl.TestContextImpl.fail(TestContextImpl.java:335)
	at io.vertx.ext.unit.JUnitTest$AwaitAsyncTestSuite.lambda$testAwaitWithTimeout$2(JUnitTest.java:726)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-715" java.lang.AssertionError: expected
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:467)
	at io.vertx.ext.unit.impl.TestContextImpl.fail(TestContextImpl.java:335)
	at io.vertx.ext.unit.JUnitTest$AwaitAsyncTestSuite.lambda$testAwaitWithFailure$1(JUnitTest.java:704)
	at java.lang.Thread.run(Thread.java:748)
Unhandled exception 
java.lang.AssertionError: Testing async failure
	at org.junit.Assert.fail(Assert.java:88)
	at io.vertx.ext.unit.JUnitTest$ThirdPartyAssertAsyncFailure.lambda$null$0(JUnitTest.java:1084)
	at io.vertx.ext.unit.impl.TestContextImpl.verify(TestContextImpl.java:400)
	at io.vertx.ext.unit.JUnitTest$ThirdPartyAssertAsyncFailure.lambda$failWithAsync$1(JUnitTest.java:1084)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Failure in calling handler 
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.vertx.ext.unit.JUnitTest$DeployFailingVerticle.lambda$before$0(JUnitTest.java:986)
	at io.vertx.core.impl.DeploymentManager.lambda$reportResult$6(DeploymentManager.java:448)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Unhandled exception 
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.vertx.ext.unit.JUnitTest$DeployFailingVerticle.lambda$before$0(JUnitTest.java:986)
	at io.vertx.core.impl.DeploymentManager.lambda$reportResult$6(DeploymentManager.java:448)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Tests run: 36, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.912 sec - in io.vertx.ext.unit.JUnitTest

Results :

Failed tests: 
  TestSuiteNoEventLoopAsyncTest>TestSuiteTestBase.runTestWithAsyncCompletionAfterFailureInTest:297 null

Tests run: 295, Failures: 1, Errors: 0, Skipped: 0

[ERROR] There are test failures.

Please refer to /tmp/tmpw9yka2ur/vertx-unit/target/surefire-reports for the individual test results.
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ vertx-unit ---
[INFO] Building jar: /tmp/tmpw9yka2ur/vertx-unit/target/vertx-unit-3.5.1.jar
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ vertx-unit ---
[INFO] Building jar: /tmp/tmpw9yka2ur/vertx-unit/target/vertx-unit-3.5.1-sources.jar
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-sources) @ vertx-unit ---
[INFO] Building jar: /tmp/tmpw9yka2ur/vertx-unit/target/vertx-unit-3.5.1-test-sources.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:test-jar (attach-test-jar) @ vertx-unit ---
[INFO] Building jar: /tmp/tmpw9yka2ur/vertx-unit/target/vertx-unit-3.5.1-tests.jar
[INFO] 
[INFO] --- maven-assembly-plugin:3.2.0:single (package-sources) @ vertx-unit ---
[INFO] Building jar: /tmp/tmpw9yka2ur/vertx-unit/target/vertx-unit-3.5.1-sources.jar
[INFO] 
[INFO] --- maven-assembly-plugin:3.2.0:single (package-docs) @ vertx-unit ---
[INFO] Building zip: /tmp/tmpw9yka2ur/vertx-unit/target/vertx-unit-3.5.1-docs.zip
[INFO] 
[INFO] --- maven-assembly-plugin:3.2.0:single (default) @ vertx-unit ---
[INFO] Building jar: /tmp/tmpw9yka2ur/vertx-unit/target/vertx-unit-3.5.1-jar-with-dependencies.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:54 min
[INFO] Finished at: 2020-07-30T16:34:16Z
[INFO] ------------------------------------------------------------------------
